version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: task-app-prafful
    container_name: task-app-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: latent_assessment
      DB_USERNAME: laravel
      DB_PASSWORD: password
    networks:
      - task-app-network

  web:
    image: nginx:alpine
    container_name: task-app-web
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - task-app-network

  db:
    image: mysql:8.0
    container_name: task-app-db
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_USER: ${DB_USERNAME:-laravel}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - task-app-network

networks:
  task-app-network:
    driver: bridge

volumes:
  dbdata:
